# Generated by Django 5.0.6 on 2024-12-12 02:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_remove_forum_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forum",
            name="photo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
