# Generated by Django 5.0.6 on 2024-12-12 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_remove_verificationcode_user_verificationcode_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VerificationCode",
        ),
    ]
