# Generated by Django 5.0.6 on 2024-12-12 20:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
