# Generated by Django 5.0.6 on 2024-12-13 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0011_verificationcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationcode",
            name="code",
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name="verificationcode",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
